apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"wordpress","namespace":"q3-default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordpress"}},"template":{"metadata":{"labels":{"app":"wordpress"}},"spec":{"containers":[{"command":["/bin/sh","-c","while true; do echo 'WordPress is running...' \u003e\u003e /var/log/wordpress.log; sleep 5; done"],"image":"wordpress:php8.2-apache","name":"wordpress","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2026-01-05T14:00:40Z"
  generation: 1
  labels:
    app: wordpress
  name: wordpress
  namespace: q3-default
  resourceVersion: "730957"
  uid: 4c853daa-762d-453b-93fc-b4d9b2589b3f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo 'WordPress is running...' >> /var/log/wordpress.log;
          sleep 5; done
        image: wordpress:php8.2-apache
        imagePullPolicy: IfNotPresent
        name: wordpress
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: data
            mountPath: /var/log/wordpress.log
          - name: folder
            mountPath: /var/log

      initContainers:
        - name: sidecar
          image: busybox:stable
          restartPolicy: Always
          command: ['sh', '-c', 'tail -f /var/log/wordpress.log']
          volumeMounts:
            - name: data
              mountPath: /var/log/wordpress.log
            - name: folder
              mountPath: /var/log

      volumes:
      - name: folder
        hostPath:
          # Ensure the file directory is created.
          path: /var/log/
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /var/log/wordpress.log
          type: FileOrCreate



      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
